server:
  port: 8082

spring:
  application:
    name: ms-spring-webflux-nosql
  data:
    mongodb:
      uri: ${MONGODB_URI}

rapidapi:
  base-url: ${RAPIDAPI_BASE_URL}
  path: ${RAPIDAPI_PATH}
  host: ${RAPIDAPI_HOST}
  key: ${RAPIDAPI_KEY}
  timeout-seconds: 15

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html