server:
  port: 8084

spring:
  application:
    name: InstgranIA_SQL
  r2dbc:
    url: r2dbc:postgresql://ep-noisy-rain-anq1bkk7-pooler.c-6.us-east-1.aws.neon.tech/api_instagram?sslMode=require
    username: neondb_owner
    password: npg_tWwEiO36fqGM
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

rapidapi:
  key: 1987249da0msh6f674509859f8a2p10a9dejsn8d6d1b059dbb
  host: instagram120.p.rapidapi.com
  base-url: https://instagram120.p.rapidapi.com

logging:
  level:
    org.springframework.r2dbc: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
