# kubectl create namespace marilyn-vilapuma-44-namespace (COMANDO)
# kubectl apply -f marilyn-vilcapuma-44-namespace.yml (yml)
apiVersion: v1
kind: Namespace
metadata:
  name: marilyn-vilcapuma-44-namespace