# kubectl apply -f marilyn-vilcapuma-44-secret.yml
apiVersion: v1
kind: Secret
metadata:
    name: marilyn-vilcapuma-44-secret
    namespace: marilyn-vilcapuma-44-namespace
type: Opaque
data:
    MONGODB_URI: bW9uZ29kYitzcnY6Ly9tYXJpbHluYW5neV9kYl91c2VyOkNZN3FLN1QyOVlNYW5YMG9AY2x1c3RlcjAubWJrdHNucC5tb25nb2RiLm5ldC80NF9tYXJpbHluX3ZpbGFwdW1hP2FwcE5hbWU9Q2x1c3RlcjA=
    RAPIDAPI_BASE_URL: aHR0cHM6Ly9haS1kZXRlY3Rpb240LnAucmFwaWRhcGkuY29t
    RAPIDAPI_PATH: L3YxL2FpLWRldGVjdGlvbi1yYXBpZC1hcGk=
    RAPIDAPI_HOST: YWktZGV0ZWN0aW9uNC5wLnJhcGlkYXBpLmNvbQ==
    RAPIDAPI_KEY: MTk4NzI0OWRhMG1zaDZmNjc0NTA5ODU5ZjhhMnAxMGE5ZGVqc244ZDZkMWIwNTlkYmI=




