# kubectl apply -f marilyn-vilcapuma-44-secret.yml
apiVersion: v1
kind: Secret
metadata:
    name: marilyn-vilcapuma-44-secret
    namespace: marilyn-vilcapuma-44-namespace
type: Opaque
data:
    MONGODB_URI: <BASE64_DE_TU_MONGODB_URI>
    RAPIDAPI_BASE_URL: <BASE64_DE_TU_RAPIDAPI_BASE_URL>
    RAPIDAPI_PATH: <BASE64_DE_TU_RAPIDAPI_PATH>
    RAPIDAPI_HOST: <BASE64_DE_TU_RAPIDAPI_HOST>
    RAPIDAPI_KEY: <BASE64_DE_TU_RAPIDAPI_KEY>




