# kubectl apply -f marilyn-vilcapuma-44-serivice.yml
apiVersion: v1
kind: Service
metadata:
  name: marilyn-vilcapuma-44-service
  namespace: marilyn-vilcapuma-44-namespace
spec:
  type: NodePort      #30000-32767  # Cambia a LoadBalancer si estás en un entorno de nube
  ports:
    - port: 8082       # Puerto que el Service expondrá
      targetPort: 8082  # Puerto en el contenedor donde tu aplicación escucha
      nodePort: 30001   # Puerto asignado en el nodo, opcional
  selector:
    app: marilyn-vilcapuma-44-deployment  # Debe coincidir con las etiquetas del Deployment